import sqlite3 as sql
conn = sql.connect('class_schedule_medd.db')
c = conn.cursor()
c.execute("""create table classroom (number text, capacity integer)""")
c.execute("insert into classroom Values ('R1', 25),"
                                       "('R2', 45),"
                                       "('R3', 35),"
                                       "('R4', 45),"
                                       "('R5', 35),"
                                       "('R6', 40),"
                                       "('R7', 45),"
                                       "('R8', 35),"
                                       "('R9', 45),"
                                       "('R10', 35),"
                                       "('R11', 40),"
                                       "('R12', 45),"
                                       "('R13', 25),"
                                       "('R14', 35),"
                                       "('R15', 35),"
                                       "('R16', 40),"
                                       "('R17', 45),"
                                       "('R18', 25),"
                                       "('R19', 30),"
                                       "('R20', 40)")
c.execute("""create table timeslot (id text, time text)""")
c.execute("insert into timeslot Values ('TS1', 'MW 09:30 - 10:45'),"
                                          "('TS2', 'MW 11:00 - 12:15'),"
                                          "('TS3', 'MW 12:30 - 01:45'),"
                                          "('TS4', 'MW 02:00 - 03:15'),"
                                          "('TS5', 'TR 09:30 - 10:45'),"
                                          "('TS6', 'TR 11:00 - 12:15'),"
                                          "('TS7', 'TR 12:30 - 01:45'),"
                                          "('TS8', 'TR 02:00 - 03:15')")
c.execute("""create table instructor (number text, name text)""")
c.execute("insert into instructor Values ('I1', 'Dr. Ahmed'),"
                                        "('I2', 'Dr. Mariam'),"
                                        "('I3', 'Dr. Amna'),"
                                        "('I4', 'Dr. Sara'),"
                                        "('I5', 'Dr. Ebrahim'),"
                                        "('I6', 'Dr. Mohamed'),"
                                        "('I7', 'Dr. Faisal'),"
                                        "('I8', 'Dr. Reem'),"
                                        "('I9', 'Dr. Fahad'),"
                                        "('I10', 'Dr. Ali'),"
                                        "('I11', 'Dr. Omar'),"
                                        "('I12', 'Dr. Fatima'),"
                                        "('I13', 'Dr. Yousif'),"
                                        "('I14', 'Dr. Hessa')")
c.execute("""create table course_instructor (course_number text, instructor_number text)""")
c.execute("insert into course_instructor Values ('C1', 'I1'),"
                                               "('C1', 'I2'),"
                                               "('C2', 'I1')," 
                                               "('C2', 'I2')," 
                                               "('C2', 'I3')," 
                                               "('C3', 'I1'),"
                                               "('C3', 'I2'),"
                                               "('C4', 'I3'),"
                                               "('C4', 'I4'),"
                                               "('C5', 'I4'),"
                                               "('C6', 'I1'),"
                                               "('C6', 'I3'),"
                                               "('C7', 'I2'),"
                                               "('C7', 'I4'),"
                                               "('C8', 'I5'),"
											   "('C9', 'I5'),"
											   "('C10','I1'),"
                                               "('C10','I2'),"
                                               "('C11', 'I9'),"
                                               "('C11', 'I10'),"
                                               "('C12', 'I11')," 
                                               "('C12', 'I12')," 
                                               "('C12', 'I13')," 
                                               "('C13', 'I11'),"
                                               "('C13', 'I12'),"
                                               "('C14', 'I13'),"
                                               "('C14', 'I14'),"
                                               "('C15', 'I14'),"
                                               "('C16', 'I1'),"
                                               "('C16', 'I3'),"
                                               "('C17', 'I9'),"
                                               "('C17', 'I8'),"
                                               "('C18', 'I5'),"
											   "('C19', 'I10'),"
											   "('C20','I11'),"
                                               "('C20','I12'),"
                                               "('C21', 'I3'),"
                                               "('C22', 'I12'),"
                                               "('C23', 'I14'),"
                                               "('C24', 'I6'),"
											   "('C24', 'I7'),"
											   "('C25','I7'),"
                                               "('C25','I8')")

c.execute("""create table course (number text, name text, max_numb_of_students)""")
c.execute("insert into course Values ('C1', 'ESMA603', 25),"
                                    "('C2', 'ECCE610', 35)," 
                                    "('C3', 'ESMA610', 25),"
                                    "('C4', 'ECCE635', 30),"
                                    "('C5', 'ECCE673', 35),"
                                    "('C6', 'MEEN601', 45),"
                                    "('C7', 'MEEN613', 45),"
                                    "('C8', 'COSC604', 30),"
                                    "('C9', 'COSC606', 40),"
                                    "('C10','ESMA617', 40),"
                                    "('C11', 'ECCEXXX', 35)," 
                                    "('C12', 'ESMAXXX', 25),"
                                    "('C13', 'ECCEXXX', 30),"
                                    "('C14', 'ECCEXXX', 35),"
                                    "('C15', 'MEENXXX', 45),"
                                    "('C16', 'MEENXXX', 45),"
                                    "('C17', 'COSCXXX', 30),"
                                    "('C18', 'COSCXXX', 40),"
                                    "('C19', 'ECCEXXX', 35)," 
                                    "('C20', 'ESMAXXX', 25),"
                                    "('C21', 'MEENXXX', 45),"
                                    "('C22', 'CHEGXXX', 30),"
                                    "('C23', 'CHEGXXX', 40),"
                                    "('C24', 'CHEGXXX', 35)," 
                                    "('C25', 'ESMAXXX', 25)")

c.execute("""create table student_group (name text)""")
c.execute("insert into student_group Values ('ESM'),"
                                  "('ECE'),"
                                  "('ME'),"
                                  "('CHE'),"
                                  "('CS')")
c.execute("""create table student_group_course (name text, class_numb text)""")
c.execute("insert into student_group_course Values ('ESM', 'C1'),"
                                         "('ECE',  'C2'),"
                                         "('ESM', 'C3'),"
                                         "('ECE',  'C4'),"
                                         "('ECE',  'C5'),"
                                         "('ME',  'C6'),"
                                         "('ME',  'C7'),"
                                         "('CS',  'C8'),"
                                         "('CS',  'C9'),"
                                         "('ESM', 'C10'),"
                                         "('ECE', 'C11'),"
                                         "('ESM',  'C12'),"
                                         "('ECE', 'C13'),"
                                         "('ECE',  'C14'),"
                                         "('ME',  'C15'),"
                                         "('ME',  'C16'),"
                                         "('CS',  'C17'),"
                                         "('CS',  'C18'),"
                                         "('ECE',  'C19'),"
                                         "('ESM', 'C20'),"
                                         "('ME',  'C21'),"
                                         "('CHE',  'C22'),"
                                         "('CHE',  'C23'),"
                                         "('CHE',  'C24'),"
                                         "('ESM', 'C25')")

conn.commit()
c.close()
conn.close()